spring:
  profiles:
#    active: @profileActive@
    active: dev
  application:
    name: gb28181-client

server:
  port: ${CLIENT_PORT:8085}

# 28181 SIP服务器的配置
sip-server:
  # [必须修改] 本机的IP
  ip: 120.26.9.242
#  ip: ${SIP_IP:192.168.100.25}
  # 28181服务监听的端口
  port: 42015
#  port: ${SIP_PORT:5060}
  # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
  # 后两位为行业编码，定义参照附录D.3
  # 3701020049标识山东济南历下区 信息行业接入
  domain: ${SIP_DOMAIN:3401040049}
  id: ${SIP_ID:34010400492000000001}
  # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
  password: ${SIP_PASSWORD:123456}
  #心跳周期
  keepaliveTimeOut: 30

#作为28181设备的配置
sip-device:
  # [必须修改] 本机的IP
  ip: ${DEVICE_IP:127.0.0.1}
  # 28181服务监听的端口
  port: ${DEVICE_PORT:5065}
  #
  id: ${DEVICE_ID:34010400490000009006}
  #    id: 34010400491320000001
  #默认设备认证密码
  password: ${DEVICE_PASSWORD:123456}

